### ISSUE TITLE
Tried to run the container but shuts down immediately

### ISSUE THREAD

**Issue by ferry-j-ispnext** [D3strukt0r/docker-spigot#3] opened 2020-12-18 10:30 UTC
**Describe the bug**
When running:
`
docker run \
    --rm \
    -d \
    -p 25565:25565 \
    -v $(pwd)/spigot:/app \
    -e JAVA_MAX_MEMORY=1G \
    -e EULA=true \
    --name spigot \
    d3strukt0r/spigot
`
the container immediately shuts down. When removing the --rm parameter, it is trying to start the MC server but nothing else happens.

There is a folder created with three files in there:
![image](https://user-images.githubusercontent.com/17270672/102604170-14e34980-4124-11eb-8369-30d74f481dae.png)

Logs of the container:
![image](https://user-images.githubusercontent.com/17270672/102604283-3e03da00-4124-11eb-913b-c2c2ca9f3dae.png)

**To Reproduce**
Described above

**Expected behavior**
The spigot server to run

**Screenshots**
See above

**Desktop (please complete the following information):**

-   OS: MacOS 11.1
-   Docker Desktop 3.0.1 (50773)

**Comment by ferry-j-ispnext** [comment] 2021-01-04 19:41
Any thoughts on this?

**Comment by D3strukt0r** [comment] 2021-01-20 10:40
First, thank you @ferryferry for this contribution :), I'm really sorry, i was just told about this issue, didn't get any notifications.

Secondly, the problem is that right now there is a complex startup command to allow the user to send commands with "docker run <name> console <command>".
I removed that and made it simpler in the dev build. Could you try it wirh "d3strukt0r/spigot:nightly" and tell me how that resulted

**Comment by ferry-j-ispnext** [comment] 2021-01-20 10:50
Haha no problem, could happen!

I 'ferryfied' it (making jokes about my own name) and is seems to work with the nightly tag.
![image](https://user-images.githubusercontent.com/17270672/105164541-8a707a00-5b15-11eb-82f4-983dc75410fb.png)
Even loaded Dynmap as plugin, as you can see in the screenshot.

**Comment by D3strukt0r** [comment] 2021-01-21 16:25
Thanks for that. Yeah wouldn't have gotten the joke otherwise xD
The problem with this "new" startup method, is that I don't have a "layer" in-between anymore to catch output or send commands. So basically, during setup, you'd have to start interactively and set everything up (docker run -it ...), and no docker-compose wouldn't work either. Once everything is set up, you could run it in the background in whatever way.

Bash or Linux generally is not my strength, but I'm pretty certain there is still a way to get into the console in another way, but who known when I figure that out. Unless someone out there actually knows already :)

I'll keep this issue open until that happens. The CI might close it anyways ...

Keep in mind, the nightly build is always gonna have the latest spigot version, or at least it should.

**Comment by D3strukt0r** [comment] 2021-04-07 12:28
Fixed with 180dbc92a6e7771a67f3d4596ffce574bd906eb0. Will disable ability to send commands through the console though (except when using `docker run -it ...`, and only then)

**Closed as completed by D3strukt0r** 2021-04-07 12:28 UTC
Labels: bug, help wanted, no-issue-activity
